// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nomfyxjlbegmdvmrpzsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vbWZ5eGpsYmVnbWR2bXJwenNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0Njc5MzcsImV4cCI6MjA1NzA0MzkzN30.fLHA4HbuuB7RJSzST9iykCZJAX7CQGqbqR208H8NLC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);